### ISSUE TITLE
Monitor mode works but doesn't capture handshakes

### ISSUE THREAD

**Issue by TheLittleYellowFiat** [cyberknight777/nethunter_kernel_xiaomi_vayu#2]
I am trying to capture a handshake using Airodump-ng, the monitor starts but it doesn't capture a handshake, I tried disconnecting the client and reconnecting it again to force a handshake but had no luck. My phone is the POCO X3 Pro 8/256, the firmware was installed through TWRP, the NetErnels kernel modules are running in Magisk (I checked). I also tried using WiFite, it didn't work but I tried it on a Raspberry Pi (from which i successfully captured a handshake using Airodump-ng), and it also couldn't capture the handshake.

Airodump-ng command I used:
sudo airodump-ng wlan0 -c 8 -w Test

Is there something I am doing blatantly wrong, or is there something wrong with my installation?

**Comment by cyberknight777** [comment]
it wont work with wlan0.

**Comment by mf-rl** [comment]
@TheLittleYellowFiat Try with an external wifi adapter. I just tried it with a TP-Link TL-WN722N. It loads by default as wlan2. I have same device as you, with CrDroid custom rom and @cyberknight777 's kernel and modules. I haven't installed anything else, and it is working good.

**Comment by cyb3rsec1990** [comment]
@YawarPandar Can I ask what version of crdroid did you use?

**Comment by mf-rl** [comment]
@cyb3rsec1990 currently, I'm on crDroid 8.9 (Android 12).

**Comment by cyb3rsec1990** [comment]
One thing pls,,I'm currently at evolution X with kangarooX kernel, can I flash crdroid with this rom?

**Comment by cyb3rsec1990** [comment]
@YawarPandar

**Comment by mf-rl** [comment]
Well...you can try, but I think it won't work. I'm pretty sure custom kernels are built for specific roms and specific Android versions. Also, as @cyberknight777 states [here ](https://github.com/cyberknight777/nethunter_kernel_xiaomi_vayu/issues/4#issuecomment-1286453866), this is for crDroid only. 
I think you could try to get the source code for the KangarooX kernel you are currently using, patch it and build your own kernel for NetHunter.

**Comment by cyb3rsec1990** [comment]
I see thanks for replying, @YawarPandar . I hope @cyberknight777 will create kernel for my rom..
