### ISSUE TITLE
Doesn't build with gcc or neutron-clang

### ISSUE THREAD

**Issue by BlueGradientHorizon** [cyberknight777/nethunter_kernel_xiaomi_vayu#3]
The first option I tried to build the kernel was `export COMPILER=clang`. In this case, your script should download the archive - `wget https://gitlab.com/dakkshesh07/neutron-clang/-/archive/Neutron-15/neutron-clang-Neutron-15.zip`. But it is no longer available, and instead the author of that repository offers a download of version 16 of neutron-clang. I modified your script a bit to download another archive - `wget https://gitlab.com/dakkshesh07/neutron-clang/-/archive/0be833248fe825947be718565fbe5597808539f7/neutron-clang-0be833248fe825947be718565fbe5597808539f7.zip` But as soon as I start the build process, an error is displayed
```
arch/arm64/Makefile:96: *** arm-linux-gnueabi-gcc not found, check CROSS_COMPILE_ARM32. stop.
```
This version of clang does not have a gcc compiler, so the build cannot continue.

The second option was `export COMPILER=gcc`. All files are downloaded successfully, but the build ends quickly. The complete build log using gcc is attached
[log-gcc.txt](https://github.com/cyberknight777/nethunter_kernel_xiaomi_vayu/files/9331846/log-gcc.txt)

**Comment by cyberknight777** [comment]
uh, why don't you change every call of -15 to -16 instead

**Comment by BlueGradientHorizon** [comment]
I can't use the latest version of neutron-clang because clang requires glibc version 2.36, which is not yet available in the Ubuntu repository (I'm using 22.04.1).
```
clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36` not found (required by clang)
```

**Comment by cyberknight777** [comment]
use docker

**Comment by cyberknight777** [comment]
Or use https://gist.github.com/dakkshesh07/240736992abf0ea6f0ee1d8acb57a400

**Comment by Mikdadali** [comment]
where we need to paste that code @cyberknight777
