### ISSUE TITLE
OS not loading after flashing kernel

### ISSUE THREAD

**Issue by mf-rl** [cyberknight777/nethunter_kernel_xiaomi_vayu#4]
Hi!
I just tried flashing kernel. I followed these steps:
- Flashed kali nethunter lite 2022.3 arm64 with Magisk
- Flashed kernel with TWRP (also tried with FKM)

After this, OS won't boot. It just stays in the initial POCO screen forever.
I'm a complete newbie here, and I understand maybe I'm missing something. Like is this for CrDroid rom only?
I'm on MIUI 13 stock rom, vayu rooted device. Nethunter installed (had to enter some commands to fix permissions). I just wanted to try if this works
Also, thank you for your work!

**Comment by cyberknight777** [comment]
It's for CrDroid only

**Comment by mf-rl** [comment]
Got it! I'll try installing CrDroid first then. Thank you!
