### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by brain72** [cyberknight777/nethunter_kernel_xiaomi_vayu#5]
Bluetooth crs v4 is not working, interface is down when I try to scan devices ![Screenshot_20221026-171115_NetHunter Terminal](https://user-images.githubusercontent.com/13281450/198161701-1c6077b8-00b8-40eb-9645-e96b80a61f24.png)
![Screenshot_20221026-170900_NetHunter](https://user-images.githubusercontent.com/13281450/198161705-412a39e9-e93a-4792-a651-eba892a3f885.png)

**Comment by cyberknight777** [comment]
Load the module with https://github.com/neternels/addonapp/releases

**Comment by brain72** [comment]
the same error with this 

![Screenshot_20221026-203345_NetErnels Addon](https://user-images.githubusercontent.com/13281450/198185133-a899f474-d497-4a8e-bc7c-fece800952e7.png)

**Comment by cyberknight777** [comment]
Did you even load the hci stuff?

**Comment by brain72** [comment]
Yes, I can't up my bt

![Screenshot_20221026-205557_NetHunter Terminal](https://user-images.githubusercontent.com/13281450/198187779-8a852131-87b9-4c1e-ae39-f20679a2e1d7.png)

**Comment by brain72** [comment]
Maybe this helps

![Screenshot_20221026-211616_Chrome](https://user-images.githubusercontent.com/13281450/198190254-8b45ae50-b4d6-4740-b5c4-a6045b8faf8f.png)


![Screenshot_20221026-211619_Chrome](https://user-images.githubusercontent.com/13281450/198190196-9dd99d20-8f5c-4857-b796-cad9c2fe91a3.png)

**Comment by MrR0b0X** [comment]
> Yes, I can't up my bt
> 
> ![Screenshot_20221026-205557_NetHunter Terminal](https://user-images.githubusercontent.com/13281450/198187779-8a852131-87b9-4c1e-ae39-f20679a2e1d7.png)

are you sure this adapter isn't fake? i had the same bug

**Comment by brain72** [comment]
> > Yes, I can't up my bt
> > ![Screenshot_20221026-205557_NetHunter Terminal](https://user-images.githubusercontent.com/13281450/198187779-8a852131-87b9-4c1e-ae39-f20679a2e1d7.png)
> 
> are you sure this adapter isn't fake? i had the same bug

How can I check that? The bt USB is working in my laptop

![Screenshot_20221027-095609_Gmail~2](https://user-images.githubusercontent.com/13281450/198352802-106bfecc-7a1a-4f98-97a2-c4ac012c47ce.png)

**Comment by MrR0b0X** [comment]
> > > Yes, I can't up my bt
> > > ![Screenshot_20221026-205557_NetHunter Terminal](https://user-images.githubusercontent.com/13281450/198187779-8a852131-87b9-4c1e-ae39-f20679a2e1d7.png)
> > 
> > 
> > are you sure this adapter isn't fake? i had the same bug
> 
> How can I check that? The bt USB is working in my laptop
> 
> ![Screenshot_20221027-095609_Gmail~2](https://user-images.githubusercontent.com/13281450/198352802-106bfecc-7a1a-4f98-97a2-c4ac012c47ce.png)

Hmm, try type `rfcomm -a`

**Comment by brain72** [comment]
![Screenshot_20221027-110949_NetHunter Terminal](https://user-images.githubusercontent.com/13281450/198366296-0df3798d-4124-4f81-8cf1-d16310678e61.png)

**Comment by MrR0b0X** [comment]
> ![Screenshot_20221027-110949_NetHunter Terminal](https://user-images.githubusercontent.com/13281450/198366296-0df3798d-4124-4f81-8cf1-d16310678e61.png)

try also in pc

**Comment by brain72** [comment]
![Screenshot_20221027-114135_Gmail](https://user-images.githubusercontent.com/13281450/198372768-b791d163-c02b-42c6-bc20-c05d548b9161.png)

**Comment by MrR0b0X** [comment]
> ![Screenshot_20221027-114135_Gmail](https://user-images.githubusercontent.com/13281450/198372768-b791d163-c02b-42c6-bc20-c05d548b9161.png)

`rfcomm -i hci0`

**Comment by brain72** [comment]
![Screenshot_20221027-174410_Gmail](https://user-images.githubusercontent.com/13281450/198423504-eb36883e-de24-44b3-b032-b43cdecf1bb8.png)
![Screenshot_20221027-174245_NetHunter Terminal](https://user-images.githubusercontent.com/13281450/198423509-457eb93a-a787-40c5-b12c-50b1864afc89.png)

**Comment by MrR0b0X** [comment]
> Did you even load the hci stuff?

i checked modules.zip, there is no hci stuff so it's built-in

**Comment by MrR0b0X** [comment]
> ![Screenshot_20221027-174410_Gmail](https://user-images.githubusercontent.com/13281450/198423504-eb36883e-de24-44b3-b032-b43cdecf1bb8.png) ![Screenshot_20221027-174245_NetHunter Terminal](https://user-images.githubusercontent.com/13281450/198423509-457eb93a-a787-40c5-b12c-50b1864afc89.png)
`rfkill block bluetooth && rfkill unblock bluetooth && service bluetooth restart && hciconfig hci0 up`

**Comment by brain72** [comment]
Same problem 
![Screenshot_20221102-163801_NetHunter Terminal](https://user-images.githubusercontent.com/13281450/199622171-d2628df6-98db-4ef3-b1bd-34a5259d7d55.png)

**Comment by MrR0b0X** [comment]
> Same problem ![Screenshot_20221102-163801_NetHunter Terminal](https://user-images.githubusercontent.com/13281450/199622171-d2628df6-98db-4ef3-b1bd-34a5259d7d55.png)

Can you show me the shape of the adapter you have and its box as well?

**Comment by brain72** [comment]
![IMG_20221106_125007](https://user-images.githubusercontent.com/13281450/200194457-f6c31bd5-bc58-4b64-a1f2-0ee91e7f5c83.jpg)

**Comment by MrR0b0X** [comment]
> ![IMG_20221106_125007](https://user-images.githubusercontent.com/13281450/200194457-f6c31bd5-bc58-4b64-a1f2-0ee91e7f5c83.jpg)

weird, maybe @yesimxev know, he have the same adapter

**Comment by yesimxev** [comment]
Show me a `hciconfig -a`

**Comment by brain72** [comment]
![Screenshot_20221107-210615_NetHunter Terminal](https://user-images.githubusercontent.com/13281450/200479851-22f6d2cf-79df-46ce-a180-b06732f97916.png)

**Comment by yesimxev** [comment]
I think it's a dumb adapter with the auto pairing so it can't be even controlled if you plug into Windows. Policy should say the following 
![Screenshot_20221108-081754_NetHunter_Terminal](https://user-images.githubusercontent.com/23633302/200513404-39ad0310-d3da-469a-82f0-f9de8c83774f.png)

**Comment by brain72** [comment]
> I think it's a dumb adapter with the auto pairing so it can't be even controlled if you plug into Windows. Policy should say the following ![Screenshot_20221108-081754_NetHunter_Terminal](https://user-images.githubusercontent.com/23633302/200513404-39ad0310-d3da-469a-82f0-f9de8c83774f.png)

im gonna try in my laptop and with a different adapter, thanks

**Comment by yesimxev** [comment]
Sure, let me know how it went. Looks like my adapter is same but straight, not curved

**Comment by MrR0b0X** [comment]
> Sure, let me know how it went. Looks like my adapter is same but straight, not curved

Um can you show its shape?

**Comment by yesimxev** [comment]
![Screenshot_20221109-150500_Camera](https://user-images.githubusercontent.com/23633302/200866710-7b4ee015-e657-471f-b606-078f8ccb7e75.png)

**Comment by MrR0b0X** [comment]
> ![Screenshot_20221109-150500_Camera](https://user-images.githubusercontent.com/23633302/200866710-7b4ee015-e657-471f-b606-078f8ccb7e75.png)

![Screenshot_٢٠٢٢١١١٠-٠٢٥٧٥٤_Amazon Shopping](https://user-images.githubusercontent.com/35136385/200974354-d86ace6c-9d8e-4912-a68a-100ddc59d59d.jpg)
the base looks straight, is it the same? because I can't see it well in the picture

**Comment by yesimxev** [comment]
Yes sorry for the pic. They look the same. My old ebay link just goes to 404 as it's very old. The name was "Bluetooth Transmitter Dongle 4.0 USB 2.0 CSR 4.0 Adapter PC LAPTOP XP VISTA" from seller:
amazingprice18 (3549)
深圳市龙岗区南湾街道玉岭花园A3栋2211
深圳市, 廣東省, 518406
China
![Screenshot_20221110-124413_Gmail](https://user-images.githubusercontent.com/23633302/201095093-214afb01-a013-4b90-98e9-42610cac32de.png)
